openapi: 3.0.0
servers:
    - url: https://2295e730-ca1e-4dbb-91c0-8e7ada59ee26.mock.pstmn.io
      description: Development server
components:
  schemas:
    UserAuth:
      type: object
      properties:
        username:
          type: string
          description: Username of the user to be registered
        password:
          type: string
          description: Password for the user
    EntityCreated:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Status code of the request
        msg:
          type: string
          description: Msg of the request
    ListItem:
      type: object
      properties:
        itemName: 
          type: string
        itemsPrice:
          type: integer
          format: float
        category:
          type: string
    Favourites:
      type: object
      properties:
        listName:
          type: string
        listItems:
          type: array
          items:
            $ref:  "#/components/schemas/ListItem"
info:
  title: Ecommerce Application API Spec
  version: "1.0"
paths:
  /users:
    description: Endpoint to manage the users
    post:
      tags:
        - "Users"
      description: Create a new user in the application
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuth"
            example:
              username: "Alex"
              password: "123123"
      responses:
        "200":
          description: "User created successfully"
          content:
            application/json:
              schema:
                type: string
              example: "user was added successfully"
  /users/signin:
    description: Signin the user
    post:
      tags:
        - "Users"
      description: Sigin the user and respond with the auth token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuth"
            example:
              username: "Alex"
              password: "123123"
      responses:
        "200":
          description: Auth token send to the client
          content:
            application/json:
              schema:
                type: object
                properties:
                  authToken:
                    type: string
  /favourites:
    description: Manage the favourites list
    post:
      tags:
        - "Favourites"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Favourites"
            example:
              listName: "Electronics"
              listItems:
                - itemName: "iphone"
                  itemPrice: 778
                  category: Mobile
                - itemName: "LG tv"
                  itemPrice: 899
                  category: TV
      responses:
        "200":
          description: "The Product was added successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityCreated"
              example:
                code: 201
                msg: The favourites list was created
  /favourites/{listname}/{userid}:
    description: Manage favourites list using list name and user id
    get:
      tags:
        - "Favourites"
      parameters:
        - name: listname
          in: path
          required: true
          schema:
            type: string
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List was retrived sucessfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Favourites"
              example:
                listName: "Electronics"
                listItems:
                  - itemName: "iphone"
                    itemPrice: 778
                    category: Mobile
                  - itemName: "LG tv"
                    itemPrice: 899
                    category: TV
    delete:
      tags:
        - "Favourites"
      description: Delete a favourites list
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
        - name: listname
          in: path
          required: true
          schema:
            type: string  
        - name: authtoken   
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List was deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntityCreated"
              example:
                code: 200
                msg: List was deleted succesfully